/*
-- Query: SELECT * FROM job_tracking.profile_data
LIMIT 0, 1000

-- Date: 2018-04-04 01:50
*/
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100002,'EMPLOYER','Delvin','Gustav','Delve@aol.com','4055211234','IBM','Big guy',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'2018-03-25 02:30:38');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100003,'STUDENT','Parrot','Patches','patchy@gmail.com','9180000000',NULL,NULL,'HI','SALES','English','Russian, parrotese','Northeastern State University','Marketing','Presidents Honor roll, Future Eagles of America',0,NULL,'2018-03-25 02:30:38');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100004,'PROFESSIONAL','Pete','Pro','ppro@juno.com','9183214321',NULL,NULL,'OK','ENGINEERING','English','None',NULL,NULL,NULL,4,'Masters of Mechanical Engineering from TCC','2018-03-25 02:30:38');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100005,'STUDENT','Last','First','email@provider.com','9189189180','Company','Title','OK','COMPUTER','Language','Other Languages','School Attending','Major','Honors, Awards, Organizations',10,'Education Level','2018-03-25 02:30:38');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100007,'EMPLOYER','Canine','Tucker','tucker@my.com','9181235555','Woof, Inc','AlphaDog',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'2018-04-03 22:22:49');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100008,'STUDENT','Studious','Stu','wherever@here.net','1234567890',NULL,NULL,'AK','RETAIL','Oddish','Gurgle','Tulsa Tech','Basket Weaving','Lotsa stuff',0,NULL,'2018-03-25 02:30:38');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100009,'STUDENT','Russet','Golden','spuds@potato.com','9876543210',NULL,NULL,'RI','FINANCIAL','Yiddish','Mashed','Spud U','Home Economics','Most likely to be baked',0,NULL,'2018-03-25 02:30:38');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100010,'PROFESSIONAL','Campbell','Tom','tomato@soup.net','9874561230',NULL,NULL,'OK','SALES','English','Soupish',NULL,NULL,NULL,57,'MBA','2018-04-02 21:01:45');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100012,'EMPLOYER','Gates','Bill','boss@microsoft.com','8889991111','Microsoft','Super Nerd',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'2018-04-01 23:16:32');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100013,'EMPLOYER','Helix','Double','helix@dna.net','2223334444','Bio Side','Creator',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'2018-03-25 02:30:38');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100014,'EMPLOYER','Big','Bob','bob@bigbox.com','9991118888','','title','AK','OTHER',NULL,NULL,NULL,NULL,NULL,0,NULL,'2018-03-25 02:30:38');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100015,'EMPLOYER','Fleetfeather','Debbie','spaz@gmail.com','8765431234','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'2018-03-25 02:30:38');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100016,'STUDENT','Schmo','Joe','joe@uni.edu','3459991234',NULL,NULL,'NA','RETAIL','German','','Weave U','Masters Underwater Basketweaving','Outstanding basket 2017',0,NULL,'2018-04-02 00:40:19');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100017,'STUDENT','Brown','Sam','greatstuff@aol.com','9189876789',NULL,NULL,'NA','COMPUTER','Grump','','NSU','Psychology','',0,NULL,'2018-03-25 02:30:38');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100018,'PROFESSIONAL','Baggins','Frodo','Baggins@shire.net','8769872345',NULL,NULL,'NA','SALES','English','Hobbitish',NULL,NULL,NULL,7,'Bachelors Swordcrafting','2018-04-01 20:48:01');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100019,'EMPLOYER','Tomato','Tommy','Tommy@soup.net','2468640864','Progresso','Chief Can Opener','NA',NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'2018-04-02 21:19:00');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100020,'STUDENT','Shrub','Gus','Shrub@juno.com','1359754321',NULL,NULL,'NA','SERVICE','Italian','English, Irish','U of Hawaii','Marketing','AMA',0,NULL,'2018-04-02 21:31:38');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100021,'EMPLOYER','Grey','Gandalf','gandalf@shire.net','9184320987','Wizards R Us','Chief Operating Officer','NA',NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'2018-04-03 23:58:45');
INSERT INTO `profile_data` (`person_id`,`access_level`,`last_name`,`first_name`,`email`,`phone`,`company`,`title`,`desired_state`,`desired_category`,`primary_language`,`other_languages`,`school`,`major`,`academia`,`experience`,`education`,`last_update`) VALUES (100022,'PROFESSIONAL','Parker','Peter','Peter.Parker@Gmail.com','2347777531',NULL,NULL,'NA','ENGINEERING','English','German, French',NULL,NULL,NULL,6,'Masters Genetic Engineering','2018-04-04 01:10:23');
